### ISSUE TITLE
Error in shiny plot

### ISSUE THREAD

**Issue by mbolgermunro** [JoachimGoedhart/PlotsOfDifferences#1]
Hi Joachim,

I'm trying to use your shiny app via RStudio to plot data but can't quite get it to work. I have installed all of the dependencies and when I run the app I get no immediate errors. However, switching to the "plot" tab results in `Error: attempt to apply non-function`. This is for both my own data and the pre-loaded sample data. As you can see, the error message is not very informative so I can't easily debug this myself... Any help would be greatly appreciated! Also, running the app on your website works beautifully but I would like to run it in RStudio so I can play with some ggplot parameters.

Thanks!
Madison

**Comment by JoachimGoedhart** [comment]
Apologies for the late reply - I seem to miss notifications when issues are posted.
Did you fix it, or is the issue still existing?
